### ISSUE TITLE
We need more in the readme than "SHOESTRING" I'll try to write something up

### ISSUE THREAD

**Issue by johnkealy** [ucsf-web-services/shoestring#1]

**Comment by andrewmallis** [comment]
Credit the original project: https://github.com/PebbleRoad/tapestry ?

Is the intent to deviate from this so far that forking the actual repo, and maintaining the connection is not in the proper spirit?

**Comment by johnkealy** [comment]
We should at least add a link to the original repo.  Thanks @andrewmallis!

**Comment by Okami-** [comment]
Credit added.
