### ISSUE TITLE
align banner markup and css with UCSF Identity Web Banner Templates

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-web-services/shoestring#26]
The [UCSF Identity Web Banner Templates](https://github.com/ucsf-web-services/ucsf_identity_web_banner_templates) currently ships a banner version that renders similarly to shoestring, but uses different markup and CSS to do so.

_That is not good!_

Resolve any discrepancies between the two projects.

**Comment by stopfstedt** [comment]
refs ucsf-web-services/ucsf_identity_web_banner_templates#19

**Comment by Okami-** [comment]
Changing markup, classes, and sass after https://github.com/ucsf-web-services/ucsf_identity_web_banner_templates/pull/22 is merged.

**Comment by stopfstedt** [comment]
@Okami- , ucsf-web-services/ucsf_identity_web_banner_templates#22 has been merged.
